### ISSUE TITLE
Option width and height 

### ISSUE THREAD

**Issue by EvansPM** [tatarize/potrace-cli#1]
In my svg i need width and height  but the generated svg come without it.
But can be found on "viewBox" attrubute.

**Comment by tatarize** [comment]
Seems reasonable enough, though by default omitted width and height values in SVG are taken to be equal to 100%, and 100% should be strictly fine since it means 100% of the view you currently have. The viewbox specifies how much of a view you are occupying relating the size of the view to the values. I have pretty considerable expertise on svg and I can tell you the backend there is writing correct svgs. I'll go ahead and add it in. But, you may want to have your usecase comply a bit more with the eccentricities you'll find in svgs. Width, height, and even viewbox are all omittable. You'd then just have the values listed in raw pixels without any conversion factors established.

It'll be chanced for 0.0.4.
